version: '3'

services:
  mongo:
    image: mongo:4.2.8
    volumes:
      - db_data:/data/db
    restart: always

  server:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      SERVER_IP: "0.0.0.0"
      SERVER_PORT: 3000
      MONGODB_IP: mongo
      MONGODB_PORT: 27017
      # MONGODB_USER: ${MONGODB_USER}
      # MONGODB_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  db_data: